" set gfn=MesloLGMDZ:h18
set gfn=Cousine:h19
" set gfn=EnvyCodeR:h19
set transparency=2
set guioptions=aAce
set invmmta

" command-w plugin
macmenu &File.Close key=<nop>
nmap <D-w> :CommandW<CR>
imap <D-w> <Esc>:CommandW<CR>

" macmenu &File.New\ Tab key=<nop>
" map <D-t> <Plug>PeepOpen
