set nocompatible

" global config
filetype plugin indent on
set backspace=eol,indent,start
set backupdir=~/.vim/backup
set directory=~/.vim/backup
set encoding=utf-8
set hlsearch
set incsearch
set linebreak
set number
set ruler
syntax enable

if has ("autocmd")
  " File type detection. Indent based on filetype. Recommended.
  filetype plugin indent on
endif

" pathogen
call pathogen#infect()

" ctags
map <Leader>rt :!ctags --extra=+f -R *<CR><CR>
map <C-\> :tnext<CR>

" solarized
set background=light
colorscheme solarized

" syntastic
let g:syntastic_enable_signs=1
let g:syntastic_quiet_warnings=1

" zoomwin
map <Leader><Leader> :ZoomWin<CR>
